workspace:
  base: /drone
  path: src
pipeline:
  build:
    image: ${BASE_IMAGE}
    environment:
      - BASE_IMAGE=${BASE_IMAGE}
      - PKGDIR=/drone/src/packages
      - PORTAGE_BINHOST=https://storage.googleapis.com/gentoo.presslabs.net/packages/${DRONE_BRANCH/master/latest}
    commands:
      - ln -sf /drone/src/portage /usr/portage
      - wget -q -S --spider https://storage.googleapis.com/gentoo.presslabs.net/packages/latest/Packages
      - make Dockerfile.build
      - make packages
    when:
      event: [ push ]

  build:
    image: ${BASE_IMAGE}
    environment:
      - BASE_IMAGE=${BASE_IMAGE}
      - PKGDIR=/drone/src/packages
      - PORTAGE_BINHOST=https://storage.googleapis.com/gentoo.presslabs.net/packages/${DRONE_TAG##v}
    commands:
      - ln -sf /drone/src/portage /usr/portage
      - make Dockerfile.build
      - make packages
    when:
      event: [ tag ]

  publish-packages-to-gcs:
    image: wyattjoh/drone-gcs
    acl: public
    bucket: "gentoo.presslabs.net"
    source: packages/**/*
    strip_prefix: packages/
    cache_control: private, max-age=0
    target: /packages/${DRONE_BRANCH/master/latest}/
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: GOOGLE_APPLICATION_CREDENTIALS_CONTENTS
    when:
      event: [ push ]

  publish-packages-to-gcs:
    image: wyattjoh/drone-gcs
    acl: public
    bucket: "gentoo.presslabs.net"
    source: packages/**/*
    strip_prefix: packages/
    cache_control: private, max-age=0
    target: /packages/${DRONE_TAG##v}/
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: GOOGLE_APPLICATION_CREDENTIALS_CONTENTS
    when:
      event: [ tag ]

  publish-docker-image:
    image: plugins/docker
    mirror: https://mirror.gcr.io
    dockerfile: Dockerfile.build
    squash: true
    compress: true # we compress the context since portage can be very big
    registry: gcr.io
    repo: gcr.io/pl-infra/gentoo-builder
    username: _json_key
    tags: [ "${DRONE_BRANCH/master/latest}" ]
    force_tag: true
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: [ push ]

  publish-docker-image:
    image: plugins/docker
    mirror: https://mirror.gcr.io
    dockerfile: Dockerfile.build
    squash: true
    compress: true # we compress the context since portage can be very big
    registry: gcr.io
    repo: gcr.io/pl-infra/gentoo-builder
    username: _json_key
    tags: [ "${DRONE_TAG##v}" ]
    force_tag: true
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: [ tag ]

matrix:
  include:
    - BASE_IMAGE: docker.io/gentoo/stage3-amd64-hardened-nomultilib:20180115
