workspace:
  base: /drone
  path: src
pipeline:
  build:
    image: ${BASE_IMAGE}
    environment:
      - BASE_IMAGE=${BASE_IMAGE}
      - PKGDIR=/drone/src/packages
      - PORTAGE_BINHOST=https://pl-gentoo-packages.storage.googleapis.com/${DRONE_BRANCH/master/latest}${SUBTAG}
    commands:
      - ln -sf /drone/src/portage /usr/portage
      - make Dockerfile.build
      - make packages

  publish-packages-to-gcs:
    image: wyattjoh/drone-gcs
    acl: public
    bucket: "pl-gentoo-packages"
    source: packages/**/*
    strip_prefix: packages/
    cache_control: private, max-age=0
    target: /${DRONE_BRANCH/master/latest}${SUBTAG}/
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: GOOGLE_APPLICATION_CREDENTIALS_CONTENTS

  publish-docker-image:
    image: plugins/docker
    mirror: https://mirror.gcr.io
    dockerfile: Dockerfile.build
    squash: true
    registry: gcr.io
    repo: gcr.io/pl-infra/gentoo-builder
    username: _json_key
    tags: ["${DRONE_BRANCH/master/latest}${SUBTAG}"]
    force_tag: true
    secrets:
      - source: GOOGLE_CREDENTIALS
        target: DOCKER_PASSWORD
    when:
      event: push

matrix:
  include:
    - BASE_IMAGE: docker.io/gentoo/stage3-amd64-hardened-nomultilib:20180115
      SUBTAG:
