workspace:
  base: /drone
  path: src
pipeline:
  build:
    image: plugins/gcr
    mirror: https://mirror.gcr.io
    dockerfile: Dockerfile
    repo: gcr.io/pl-infra/gentoo-builder
    tags: [ "${DRONE_BRANCH/master/latest}", "${GENTOO_SNAPSHOT}-r${DRONE_BUILD_NUMBER}" ]
    build_args:
      - SNAPSHOT=${GENTOO_SNAPSHOT}
    secrets:
      - GOOGLE_CREDENTIALS
    when:
      event: [ push ]
matrix:
  GENTOO_SNAPSHOT:
    - "20180125"
